"""remove unread message count from chat rooms and add last message count

Revision ID: 10c12e8248eb
Revises: 8b57cc66204d
Create Date: 2024-12-16 19:30:04.200222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c12e8248eb'
down_revision = '8b57cc66204d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_timestamp', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.drop_column('unread_message_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unread_message_count', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('last_message_timestamp')

    # ### end Alembic commands ###
