"""add story and pin table

Revision ID: 2cf612e72fba
Revises: 3ee6e77b99c8
Create Date: 2024-12-14 16:53:33.200089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf612e72fba'
down_revision = '3ee6e77b99c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('tittle', sa.String(length=128), nullable=False),
    sa.Column('content', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('story_id')
    )
    op.create_table('pins',
    sa.Column('pin_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.story_id'], ),
    sa.PrimaryKeyConstraint('pin_id'),
    sa.UniqueConstraint('latitude'),
    sa.UniqueConstraint('longitude')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pins')
    op.drop_table('stories')
    # ### end Alembic commands ###
