"""add message, chat, and notification tables

Revision ID: 6897d2beaec4
Revises: e9b9ee43fb06
Create Date: 2024-12-15 13:16:40.340588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6897d2beaec4'
down_revision = 'e9b9ee43fb06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_rooms',
    sa.Column('chat_room_id', sa.Integer(), nullable=False),
    sa.Column('last_message', sa.String(length=1024), nullable=True),
    sa.Column('unread_message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('chat_room_id')
    )
    op.create_table('chat_participants',
    sa.Column('chat_room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.chat_room_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('chat_room_id', 'user_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('chat_room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1024), nullable=False),
    sa.Column('is_delivered', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.chat_room_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('NEW_MESSAGE', 'FRIEND_REQUEST', 'FRIEND_ACCEPT', 'FRIEND_POST', name='NotificationType'), nullable=False),
    sa.Column('content', sa.String(length=128), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('messages')
    op.drop_table('chat_participants')
    op.drop_table('chat_rooms')
    # ### end Alembic commands ###
