"""add friend and friend request models

Revision ID: 72abbcd7aec2
Revises: 10c12e8248eb
Create Date: 2024-12-28 11:27:34.549734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72abbcd7aec2'
down_revision = '10c12e8248eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_requests',
    sa.Column('friend_request_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='FriendRequestStatusType'), nullable=False),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('friend_request_id')
    )
    op.create_table('friends',
    sa.Column('usera_id', sa.Integer(), nullable=False),
    sa.Column('userb_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usera_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['userb_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('usera_id', 'userb_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    op.drop_table('friend_requests')
    # ### end Alembic commands ###
