services:
  web:
    depends_on:
      db:
        condition: service_healthy
    build: .
    ports:
      - 5000:5000
    secrets:
      - db-password
      - flask-secret
      - google-id
      - google-secret
    env_file:
      - .env.prod
    # environment:
      # - SECRET_KEY=/run/secrets/flask-secret
      # - GOOGLE_CLIENT_ID=/run/secrets/google-id
      # - GOOGLE_CLIENT_SECRET=/run/secrets/google-secret
      # - POSTGRES_PASSWORD_FILE=/run/secrets/db-password

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - voixdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=voixes
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  voixdb:
secrets:
  db-password:
    file: secrets/db-password.txt
  flask-secret:
    file: secrets/flask-secret.txt
  google-id:
    file: secrets/google-id.txt
  google-secret:
    file: secrets/google-secret.txt
