services:
  web:
    depends_on:
      db:
        condition: service_healthy
    build: .
    ports:
      - 5000:5000
    secrets:
      - db-password
    env_file: .env.prod
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - voixdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=voixes
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  voixdb:
secrets:
  db-password:
    file: secrets/db-password.txt
